version: '3'
services:
  backend:
    networks:
      - app-tier
    build:
      context: ./backend/mancala
    ports:
      - "8081:8081"
    depends_on:
      - db
      - redis
      - kafka
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/mancala
      - spring.datasource.username=mancala_user
      - spring.datasource.password=xyz12345
      - spring.kafka.bootstrap-servers=kafka:9093
      - spring.redis.host=redis
      - spring.redis.port=6379
#      - logging.level.org.apache.kafka.clients.producer.ProducerConfig=DEBUG
#      - logging.level.org.apache.kafka=DEBUG
    links:
      - redis

  frontend:
    networks:
      - app-tier
    build:
      context: ./frontend/mancala-app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    links:
      - backend

  nginx:
    networks:
      - app-tier
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
    depends_on:
      - frontend
      - backend

  db:
    networks:
      - app-tier
    image: postgres:latest
    environment:
      - POSTGRES_USER=mancala_user
      - POSTGRES_PASSWORD=xyz12345
      - POSTGRES_DB=mancala
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier

  kafka:
    networks:
      - app-tier
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      GROUP_ID: "mancala-game-1"
      KAFKA_CREATE_TOPICS: "game-join-request-topic:1:1,game-turn-started-topic:1:1,game-turn-expired-topic:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: elevy/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge